---
title: Use Case Catalog
description: Browse industry use cases by vertical to find the right starting point for your Adobe Experience Platform journey, with links to implementation patterns and business objectives.
doc-type: overview-page
exl-id: 7a3c2f1e-9b4d-4e6a-8f5c-2d1b3a4e7c9f
---
# Use case catalog

Industry use cases show how organizations in specific verticals apply Adobe Experience Platform and applications to achieve measurable business outcomes. Each use case describes a concrete business scenario, its expected impact, and links to the [use case pattern](/help/blueprints/use-case-patterns/overview.md) that provides detailed implementation guidance.

Browse by industry to find use cases relevant to your organization, then follow the pattern links for implementation references including decision guidance, function chains, and Experience League documentation.

| Industry | Key Themes |
| --- | --- |
| [Automotive](automotive/automotive-overview.md) | Vehicle purchase journey, service lifecycle, connected car experiences, owner loyalty |
| [B2B](b2b/b2b-overview.md) | Account-based marketing, lead scoring, pipeline acceleration, customer expansion |
| [Financial Services](financial-services/financial-services-overview.md) | Product recommendations, churn prevention, life-stage offers, fraud personalization |
| [Healthcare](healthcare/healthcare-overview.md) | Appointment management, medication adherence, patient onboarding, care coordination |
| [Insurance](insurance/insurance-overview.md) | Policy renewal, claims experience, risk prevention, cross-sell optimization |
| [Media & Entertainment](media-entertainment/media-entertainment-overview.md) | Content recommendations, subscription retention, trial conversion, cross-platform engagement |
| [Retail](retail/retail-overview.md) | Product personalization, cart recovery, cross-sell optimization, loyalty engagement |
| [Telecommunications](telecommunications/telecommunications-overview.md) | Device upgrades, churn prevention, plan optimization, network engagement |
| [Travel & Hospitality](travel-hospitality/travel-hospitality-overview.md) | Booking personalization, abandonment recovery, loyalty programs, seasonal campaigns |

## How use cases connect to implementation guidance

Each use case links to a **use case pattern** — a repeatable implementation approach that describes the function chain, decision points, and configuration steps needed to bring the use case to life. Use case patterns in turn connect to [key business objectives](/help/blueprints/business-objectives/overview.md), helping you align implementation work with strategic outcomes.

```
Industry Use Case → Use Case Pattern → Key Business Objective
```

## Browse by industry

>[!BEGINTABS]

>[!TAB Retail]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/retail/icon-abandoned-cart.png" alt="Abandoned Cart" width="40"> | [Abandoned Cart Email Recovery](retail/retail-overview.md#abandoned-cart-email-recovery) | Send personalized reminders for abandoned shopping carts | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/retail/icon-inventory-urgency.png" alt="Inventory Urgency" width="40"> | [Inventory-Based Urgency Campaigns](retail/retail-overview.md#inventory-based-urgency-campaigns) | Trigger real-time alerts when product inventory is low | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/retail/icon-price-drop.png" alt="Price Drop" width="40"> | [Price Drop Alerts](retail/retail-overview.md#price-drop-alerts) | Notify customers when wishlist or viewed items drop in price | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Out-of-Stock Notifications](retail/retail-overview.md#out-of-stock-notifications) | Notify customers when out-of-stock products become available | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/retail/icon-product-recommendations.png" alt="Product Recommendations" width="40"> | [Personalized Product Recommendations](retail/retail-overview.md#personalized-product-recommendations) | Show personalized products based on browsing and purchase history | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| <img src="assets/use-case-icons/retail/icon-category-pages.png" alt="Category Pages" width="40"> | [Personalized Category Pages](retail/retail-overview.md#personalized-category-pages) | Dynamically reorder category pages based on customer preferences | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| <img src="assets/use-case-icons/retail/icon-welcome-series.png" alt="Welcome Series" width="40"> | [New Customer Welcome Series](retail/retail-overview.md#new-customer-welcome-series) | Automate multi-email welcome series with personalized recommendations | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/retail/icon-replenishment.png" alt="Replenishment" width="40"> | [Replenishment Reminders](retail/retail-overview.md#replenishment-reminders) | Send automated reminders for regularly purchased consumable products | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/retail/icon-post-purchase.png" alt="Post-Purchase" width="40"> | [Post-Purchase Follow-Up Campaigns](retail/retail-overview.md#post-purchase-follow-up-campaigns) | Send care tips, review requests, and related product suggestions | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Social Proof Personalization](retail/retail-overview.md#social-proof-personalization) | Display personalized reviews and ratings based on customer profile | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/retail/icon-cross-sell-upsell.png" alt="Cross-Sell Upsell" width="40"> | [Cross-Sell and Upsell Recommendations](retail/retail-overview.md#cross-sell-and-upsell-recommendations) | Display relevant cross-sell and upsell products at checkout and in email | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| | [VIP Customer Exclusive Offers](retail/retail-overview.md#vip-customer-exclusive-offers) | Provide exclusive offers and early access to high-value customers | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [AI Product Advisor](retail/retail-overview.md#ai-product-advisor) | Deploy a conversational AI advisor that guides shoppers through product discovery using natural dialogue, real-time inventory, and personalized profile data. | [!BADGE Advanced]{type=Caution} | [Brand Concierge Conversational Experience](/help/blueprints/use-case-patterns/conversational-experience/brand-concierge-conversational-experience.md) |
| | [Cross-Channel Attribution Analysis](retail/retail-overview.md#cross-channel-attribution-analysis) | Measure how email, paid, and in-store touchpoints contribute to purchase conversion using multi-touch attribution models. | [!BADGE Emerging]{type=Informative} | [Customer Analytics & Insight Generation](/help/blueprints/use-case-patterns/analysis/customer-analytics-insight-generation.md) |

>[!TAB Automotive]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/automotive/icon-service-reminders.png" alt="Service Reminders" width="40"> | [Service Appointment Reminders](automotive/automotive-overview.md#service-appointment-reminders) | Send personalized service reminders based on vehicle mileage and service history | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/automotive/icon-recall-notifications.png" alt="Recall Notifications" width="40"> | [Vehicle Recall Notifications](automotive/automotive-overview.md#vehicle-recall-notifications) | Send personalized recall notifications with service scheduling options | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/automotive/icon-test-drive.png" alt="Test Drive" width="40"> | [Test Drive Scheduling](automotive/automotive-overview.md#test-drive-scheduling) | Enable personalized test drive scheduling with dealer recommendations | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/automotive/icon-model-launch.png" alt="Model Launch" width="40"> | [New Model Launch Campaigns](automotive/automotive-overview.md#new-model-launch-campaigns) | Target customers interested in new models based on current vehicle and preferences | [!BADGE Foundational]{type=Neutral} | [Batch Outbound Message Activation](/help/blueprints/use-case-patterns/campaign-management-orchestration/batch-outbound-message-activation.md) |
| <img src="assets/use-case-icons/automotive/icon-trade-in.png" alt="Trade-In" width="40"> | [Trade-In Value Campaigns](automotive/automotive-overview.md#trade-in-value-campaigns) | Proactively offer trade-in value assessments to customers ready to upgrade | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/automotive/icon-parts-accessories.png" alt="Parts Accessories" width="40"> | [Parts and Accessories Recommendations](automotive/automotive-overview.md#parts-and-accessories-recommendations) | Recommend parts and accessories based on vehicle model and ownership duration | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| <img src="assets/use-case-icons/automotive/icon-warranty.png" alt="Warranty" width="40"> | [Warranty and Extended Service Plans](automotive/automotive-overview.md#warranty-and-extended-service-plans) | Recommend warranty and service plans at optimal times based on vehicle age | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/automotive/icon-connected-car.png" alt="Connected Car" width="40"> | [Connected Car Feature Activation](automotive/automotive-overview.md#connected-car-feature-activation) | Personalize connected car feature recommendations based on vehicle capabilities | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/automotive/icon-dealer-network.png" alt="Dealer Network" width="40"> | [Dealer Network Coordination](automotive/automotive-overview.md#dealer-network-coordination) | Enable personalized dealer recommendations based on location and preferences | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/automotive/icon-vehicle-purchase.png" alt="Vehicle Purchase" width="40"> | [Vehicle Purchase Journey Personalization](automotive/automotive-overview.md#vehicle-purchase-journey-personalization) | Personalize the vehicle purchase journey from research to purchase | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| <img src="assets/use-case-icons/automotive/icon-financing.png" alt="Financing" width="40"> | [Financing and Insurance Offers](automotive/automotive-overview.md#financing-and-insurance-offers) | Present personalized financing and insurance offers based on credit profile | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| <img src="assets/use-case-icons/automotive/icon-owner-loyalty.png" alt="Owner Loyalty" width="40"> | [Owner Loyalty Programs](automotive/automotive-overview.md#owner-loyalty-programs) | Personalize loyalty communications and exclusive offers across dealer, OEM digital, and connected car channels with tier-based eligibility rules | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |

>[!TAB Financial Services]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| | [Transaction-Based Alerts and Recommendations](financial-services/financial-services-overview.md#transaction-based-alerts-and-recommendations) | Send real-time alerts for transactions and personalized recommendations | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Credit Card Application Abandonment Recovery](financial-services/financial-services-overview.md#credit-card-application-abandonment-recovery) | Re-engage customers who started but did not complete credit card applications | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Fraud Alert Personalization](financial-services/financial-services-overview.md#fraud-alert-personalization) | Personalize fraud alerts and security communications by customer preferences | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/financial-services/icon-lead-nurturing.png" alt="Lead Nurturing" width="40"> | [High-Value Lead Nurturing](financial-services/financial-services-overview.md#high-value-lead-nurturing) | Identify high-value prospects and nurture with personalized content and offers | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/financial-services/icon-account-dashboard.png" alt="Account Dashboard" width="40"> | [Personalized Account Dashboard](financial-services/financial-services-overview.md#personalized-account-dashboard) | Personalize online banking dashboard based on account activity and financial goals | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| | [Investment Portfolio Recommendations](financial-services/financial-services-overview.md#investment-portfolio-recommendations) | Provide personalized investment recommendations based on risk profile and goals | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| | [Mortgage Pre-Approval Campaigns](financial-services/financial-services-overview.md#mortgage-pre-approval-campaigns) | Target customers likely in the market for a mortgage based on profile and life stage | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/financial-services/icon-product-recommendation.png" alt="Product Recommendation" width="40"> | [Product Recommendation for Existing Customers](financial-services/financial-services-overview.md#product-recommendation-for-existing-customers) | Recommend relevant financial products based on profile, transactions, and life stage | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| <img src="assets/use-case-icons/financial-services/icon-churn-prevention.png" alt="Churn Prevention" width="40"> | [Churn Prevention Campaigns](financial-services/financial-services-overview.md#churn-prevention-campaigns) | Identify at-risk customers with AI-powered prediction and engage with retention offers | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| <img src="assets/use-case-icons/financial-services/icon-life-stage.png" alt="Life Stage" width="40"> | [Life Stage-Based Product Offers](financial-services/financial-services-overview.md#life-stage-based-product-offers) | Identify customers entering new life stages and offer relevant financial products | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Loyalty Program Engagement](financial-services/financial-services-overview.md#loyalty-program-engagement) | Personalize loyalty communications and offers across channels with real-time offer arbitration and tier-based eligibility rules | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Personalized Financial Education Content](financial-services/financial-services-overview.md#personalized-financial-education-content) | Deliver personalized financial education based on customer profile and interests | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [AI Financial Product Guide](financial-services/financial-services-overview.md#ai-financial-product-guide) | Help customers understand financial products and navigate account options through conversational AI grounded in compliance-reviewed content and real-time profile data. | [!BADGE Advanced]{type=Caution} | [Brand Concierge Conversational Experience](/help/blueprints/use-case-patterns/conversational-experience/brand-concierge-conversational-experience.md) |
| | [Product Adoption Funnel and Churn Driver Analysis](financial-services/financial-services-overview.md#product-adoption-funnel-and-churn-driver-analysis) | Identify where customers drop off in onboarding flows and which behaviors predict product attrition. | [!BADGE Emerging]{type=Informative} | [Customer Analytics & Insight Generation](/help/blueprints/use-case-patterns/analysis/customer-analytics-insight-generation.md) |

>[!TAB Healthcare]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/healthcare/icon-appointment-reminder.png" alt="Appointment Reminder" width="40"> | [Appointment Reminder Automation](healthcare/healthcare-overview.md#appointment-reminder-automation) | Send personalized appointment reminders through preferred communication channels | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/healthcare/icon-post-visit.png" alt="Post-Visit" width="40"> | [Post-Visit Follow-Up Campaigns](healthcare/healthcare-overview.md#post-visit-follow-up-campaigns) | Send post-visit surveys, care instructions, and follow-up appointment reminders | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Lab Results Notification](healthcare/healthcare-overview.md#lab-results-notification) | Notify patients when lab results are available through their preferred channel | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Insurance Coverage Verification](healthcare/healthcare-overview.md#insurance-coverage-verification) | Proactively verify and communicate insurance coverage before appointments | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Telehealth Appointment Reminders](healthcare/healthcare-overview.md#telehealth-appointment-reminders) | Send personalized reminders for telehealth appointments with connection instructions | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/healthcare/icon-preventive-care.png" alt="Preventive Care" width="40"> | [Preventive Care Reminders](healthcare/healthcare-overview.md#preventive-care-reminders) | Remind patients about recommended preventive care based on age and medical history | [!BADGE Foundational]{type=Neutral} | [Batch Outbound Message Activation](/help/blueprints/use-case-patterns/campaign-management-orchestration/batch-outbound-message-activation.md) |
| <img src="assets/use-case-icons/healthcare/icon-medication-adherence.png" alt="Medication Adherence" width="40"> | [Medication Adherence Campaigns](healthcare/healthcare-overview.md#medication-adherence-campaigns) | Send personalized reminders to help patients stay on track with medications | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Chronic Disease Management Programs](healthcare/healthcare-overview.md#chronic-disease-management-programs) | Personalize chronic disease management communications and monitoring reminders | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [New Patient Onboarding Journey](healthcare/healthcare-overview.md#new-patient-onboarding-journey) | Automate multi-step onboarding with welcome info, portal access, and scheduling | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Wellness Program Engagement](healthcare/healthcare-overview.md#wellness-program-engagement) | Personalize wellness program communications, challenges, and rewards | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Care Team Coordination](healthcare/healthcare-overview.md#care-team-coordination) | Enable personalized communication between patients and their care team | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Personalized Health Content Delivery](healthcare/healthcare-overview.md#personalized-health-content-delivery) | Deliver personalized health education content tailored to patient conditions | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Patient Journey Funnel and Care Gap Analysis](healthcare/healthcare-overview.md#patient-journey-funnel-and-care-gap-analysis) | Identify where patients disengage from care pathways and which member populations have gaps in recommended care. | [!BADGE Emerging]{type=Informative} | [Customer Analytics & Insight Generation](/help/blueprints/use-case-patterns/analysis/customer-analytics-insight-generation.md) |
| | [Patient Portal Content Personalization](healthcare/healthcare-overview.md#patient-portal-content-personalization) | Personalize the patient portal experience based on in-session browsing behavior and engagement history | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |

>[!TAB Insurance]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/insurance/icon-policy-renewal.png" alt="Policy Renewal" width="40"> | [Policy Renewal Campaigns](insurance/insurance-overview.md#policy-renewal-campaigns) | Send personalized policy renewal reminders and offers | [!BADGE Foundational]{type=Neutral} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Policy Change Notifications](insurance/insurance-overview.md#policy-change-notifications) | Send personalized notifications about policy changes and coverage updates | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Quote Abandonment Recovery](insurance/insurance-overview.md#quote-abandonment-recovery) | Re-engage customers who started but did not complete an insurance quote | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Claims Fraud Prevention](insurance/insurance-overview.md#claims-fraud-prevention) | Use intelligent fraud detection to identify suspicious claims patterns | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Catastrophic Event Response](insurance/insurance-overview.md#catastrophic-event-response) | Proactively communicate with customers in affected areas during natural disasters | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Agent and Broker Coordination](insurance/insurance-overview.md#agent-and-broker-coordination) | Enable personalized communication between customers and assigned agents | [!BADGE Foundational]{type=Neutral} | [Batch Outbound Message Activation](/help/blueprints/use-case-patterns/campaign-management-orchestration/batch-outbound-message-activation.md) |
| <img src="assets/use-case-icons/insurance/icon-claims-process.png" alt="Claims Process" width="40"> | [Claims Process Personalization](insurance/insurance-overview.md#claims-process-personalization) | Personalize claims process communications, status updates, and support resources | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Risk Assessment and Prevention](insurance/insurance-overview.md#risk-assessment-and-prevention) | Provide personalized risk assessment information and prevention tips | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Wellness and Prevention Programs](insurance/insurance-overview.md#wellness-and-prevention-programs) | Personalize wellness program communications and rewards for insurance customers | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/insurance/icon-cross-sell.png" alt="Cross-Sell" width="40"> | [Cross-Sell Product Recommendations](insurance/insurance-overview.md#cross-sell-product-recommendations) | Recommend additional insurance products based on existing policies and life stage | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| <img src="assets/use-case-icons/insurance/icon-life-stage-based-product-offers.png" alt="Life Stage" width="40"> | [Life Stage-Based Product Offers](insurance/insurance-overview.md#life-stage-based-product-offers) | Identify customers entering new life stages and offer relevant insurance products | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Discount and Savings Opportunities](insurance/insurance-overview.md#discount-and-savings-opportunities) | Identify and communicate personalized discount opportunities | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| | [Policyholder Portal Content Personalization](insurance/insurance-overview.md#policyholder-portal-content-personalization) | Personalize the authenticated portal and app experience based on behavior and policy portfolio | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |

>[!TAB Media & Entertainment]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/media-entertainment/icon-new-content.png" alt="New Content" width="40"> | [New Content Release Notifications](media-entertainment/media-entertainment-overview.md#new-content-release-notifications) | Notify subscribers about new content matching their preferences | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Watchlist and Favorites Reminders](media-entertainment/media-entertainment-overview.md#watchlist-and-favorites-reminders) | Send reminders about unwatched content in watchlists | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Live Event Viewing Reminders](media-entertainment/media-entertainment-overview.md#live-event-viewing-reminders) | Notify users about upcoming live events matching their interests | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Content Completion Campaigns](media-entertainment/media-entertainment-overview.md#content-completion-campaigns) | Remind users to finish content they started but did not complete | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/media-entertainment/icon-content-recommendations.png" alt="Content Recommendations" width="40"> | [Content Recommendation Engine](media-entertainment/media-entertainment-overview.md#content-recommendation-engine) | Provide personalized content recommendations based on viewing history | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| | [Personalized Homepage Experience](media-entertainment/media-entertainment-overview.md#personalized-homepage-experience) | Dynamically personalize homepage to show most relevant content first | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| | [Personalized Playlist Generation](media-entertainment/media-entertainment-overview.md#personalized-playlist-generation) | Automatically generate playlists based on listening history and preferences | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| | [Free Trial Conversion Campaigns](media-entertainment/media-entertainment-overview.md#free-trial-conversion-campaigns) | Engage free trial users with personalized content to encourage conversion | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Cross-Platform Content Sync](media-entertainment/media-entertainment-overview.md#cross-platform-content-sync) | Provide seamless content experience across devices with synced preferences | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| | [Social Sharing Personalization](media-entertainment/media-entertainment-overview.md#social-sharing-personalization) | Personalize social sharing prompts based on content preferences | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/media-entertainment/icon-subscription-churn.png" alt="Subscription Churn" width="40"> | [Subscription Churn Prevention](media-entertainment/media-entertainment-overview.md#subscription-churn-prevention) | Identify at-risk subscribers and engage with retention offers | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Premium Feature Upsell](media-entertainment/media-entertainment-overview.md#premium-feature-upsell) | Identify users who would benefit from premium features with personalized offers | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| | [Subscriber Churn Driver and Content Engagement Analysis](media-entertainment/media-entertainment-overview.md#subscriber-churn-driver-and-content-engagement-analysis) | Identify content engagement patterns that precede subscriber cancellation and measure retention impact by content type and cohort. | [!BADGE Emerging]{type=Informative} | [Customer Analytics & Insight Generation](/help/blueprints/use-case-patterns/analysis/customer-analytics-insight-generation.md) |

>[!TAB Telecommunications]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| | [Data Usage Alerts and Recommendations](telecommunications/telecommunications-overview.md#data-usage-alerts-and-recommendations) | Send personalized alerts when customers approach data limits | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Service Outage Notifications](telecommunications/telecommunications-overview.md#service-outage-notifications) | Proactively notify customers about service outages in their area | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [Bill Payment Reminders](telecommunications/telecommunications-overview.md#bill-payment-reminders) | Send personalized bill payment reminders with payment options | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| | [5G Upgrade Campaigns](telecommunications/telecommunications-overview.md#5g-upgrade-campaigns) | Target customers eligible for 5G upgrades with personalized offers | [!BADGE Foundational]{type=Neutral} | [Batch Outbound Message Activation](/help/blueprints/use-case-patterns/campaign-management-orchestration/batch-outbound-message-activation.md) |
| <img src="assets/use-case-icons/telecommunications/icon-plan-optimization.png" alt="Plan Optimization" width="40"> | [Plan Optimization Campaigns](telecommunications/telecommunications-overview.md#plan-optimization-campaigns) | Analyze usage patterns and recommend optimal plan changes | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [New Customer Onboarding Journey](telecommunications/telecommunications-overview.md#new-customer-onboarding-journey) | Automate personalized onboarding with welcome info and feature tutorials | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| | [Network Performance Personalization](telecommunications/telecommunications-overview.md#network-performance-personalization) | Personalize network performance information based on location and device | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/telecommunications/icon-device-upgrade.png" alt="Device Upgrade" width="40"> | [Device Upgrade Recommendations](telecommunications/telecommunications-overview.md#device-upgrade-recommendations) | Identify eligible customers and present personalized device recommendations | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| <img src="assets/use-case-icons/telecommunications/icon-churn-prevention.png" alt="Churn Prevention" width="40"> | [Churn Prevention for High-Value Customers](telecommunications/telecommunications-overview.md#churn-prevention-for-high-value-customers) | Identify high-value at-risk customers and engage with retention offers | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Family Plan Management](telecommunications/telecommunications-overview.md#family-plan-management) | Personalize communications for family plan administrators by family usage | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [Add-On Service Recommendations](telecommunications/telecommunications-overview.md#add-on-service-recommendations) | Recommend relevant add-on services based on plan, usage, and preferences | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| | [Loyalty Program Engagement](telecommunications/telecommunications-overview.md#loyalty-program-engagement) | Personalize loyalty rewards and offers across channels with real-time arbitration and tier-based eligibility constraints | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [AI Plan Advisor](telecommunications/telecommunications-overview.md#ai-plan-advisor) | Guide subscribers through personalized plan selection using conversational AI grounded in real-time usage data, account profile, and the full plan catalog. | [!BADGE Advanced]{type=Caution} | [Brand Concierge Conversational Experience](/help/blueprints/use-case-patterns/conversational-experience/brand-concierge-conversational-experience.md) |
| | [Churn Propensity and Network Experience Analytics](telecommunications/telecommunications-overview.md#churn-propensity-and-network-experience-analytics) | Correlate network quality events and service contacts with subscriber churn to identify which experience failures drive attrition. | [!BADGE Emerging]{type=Informative} | [Customer Analytics & Insight Generation](/help/blueprints/use-case-patterns/analysis/customer-analytics-insight-generation.md) |

>[!TAB Travel & Hospitality]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/travel-hospitality/icon-cart-abandonment.png" alt="Cart Abandonment" width="40"> | [Cart Abandonment Recovery Journey](travel-hospitality/travel-hospitality-overview.md#cart-abandonment-recovery-journey) | Detect abandoned booking carts and trigger personalized email journey | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-booking-reminders.png" alt="Booking Reminders" width="40"> | [Multi-Channel Booking Reminders](travel-hospitality/travel-hospitality-overview.md#multi-channel-booking-reminders) | Send personalized booking reminders via email, text, and push | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-seasonal-campaigns.png" alt="Seasonal Campaigns" width="40"> | [Seasonal Campaign Personalization](travel-hospitality/travel-hospitality-overview.md#seasonal-campaign-personalization) | Personalize campaigns based on seasonal preferences and past bookings | [!BADGE Foundational]{type=Neutral} | [Batch Outbound Message Activation](/help/blueprints/use-case-patterns/campaign-management-orchestration/batch-outbound-message-activation.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-personalized-homepage.png" alt="Personalized Homepage" width="40"> | [Personalized Homepage for New Visitors](travel-hospitality/travel-hospitality-overview.md#personalized-homepage-for-new-visitors) | Show personalized recommendations based on location and browsing behavior | [!BADGE Emerging]{type=Informative} | [Anonymous Visitor Web Personalization](/help/blueprints/use-case-patterns/personalization/anonymous-visitor-web-personalization.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-high-intent.png" alt="High-Intent" width="40"> | [High-Intent Visitor Targeting](travel-hospitality/travel-hospitality-overview.md#high-intent-visitor-targeting) | Identify high-intent visitors with AI scoring and target with personalized offers | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-post-booking-upsell.png" alt="Post-Booking Upsell" width="40"> | [Post-Booking Upsell Campaigns](travel-hospitality/travel-hospitality-overview.md#post-booking-upsell-campaigns) | Trigger upsell campaigns for upgrades, excursions, and packages after booking | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-win-back.png" alt="Win-Back" width="40"> | [Win-Back Campaigns for Lapsed Customers](travel-hospitality/travel-hospitality-overview.md#win-back-campaigns-for-lapsed-customers) | Engage lapsed customers with personalized win-back offers | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-dynamic-itinerary.png" alt="Dynamic Itinerary" width="40"> | [Dynamic Itinerary Recommendations](travel-hospitality/travel-hospitality-overview.md#dynamic-itinerary-recommendations) | Show personalized itineraries based on past bookings and preferences | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-recently-browsed.png" alt="Recently Browsed" width="40"> | [Recently Browsed Products on Homepage](travel-hospitality/travel-hospitality-overview.md#recently-browsed-products-on-homepage) | Display recently viewed destinations to encourage return visits | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-group-booking.png" alt="Group Booking" width="40"> | [Group Booking Recommendations](travel-hospitality/travel-hospitality-overview.md#group-booking-recommendations) | Recommend group packages and family-friendly options to frequent group bookers | [!BADGE Emerging]{type=Informative} | [Behavioral Recommendation](/help/blueprints/use-case-patterns/personalization/behavioral-recommendation.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-exit-intent.png" alt="Exit Intent" width="40"> | [Exit Intent Modal with Targeted Offers](travel-hospitality/travel-hospitality-overview.md#exit-intent-modal-with-targeted-offers) | Display personalized modal with relevant offers when visitor shows exit intent | [!BADGE Advanced]{type=Caution} | [Offer Decisioning](/help/blueprints/use-case-patterns/personalization/offer-decisioning.md) |
| <img src="assets/use-case-icons/travel-hospitality/icon-loyalty-program.png" alt="Loyalty Program" width="40"> | [Loyalty Program Personalization](travel-hospitality/travel-hospitality-overview.md#loyalty-program-personalization) | Personalize website, offers, and communications by loyalty tier and point balance | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| | [AI Booking Concierge](travel-hospitality/travel-hospitality-overview.md#ai-booking-concierge) | Guide guests through itinerary planning, room selection, and ancillary options using conversational AI grounded in real-time availability and loyalty profile data. | [!BADGE Advanced]{type=Caution} | [Brand Concierge Conversational Experience](/help/blueprints/use-case-patterns/conversational-experience/brand-concierge-conversational-experience.md) |

>[!TAB B2B]

| | Use Case | Description | Maturity | Pattern |
| --- | --- | --- | --- | --- |
| <img src="assets/use-case-icons/b2b/icon-webinar-demo.png" alt="Webinar Demo" width="40"> | [Webinar and Demo Scheduling](b2b/b2b-overview.md#webinar-and-demo-scheduling) | Personalize webinar invitations and demo scheduling based on prospect interests | [!BADGE Foundational]{type=Neutral} | [Event-Triggered Messaging](/help/blueprints/use-case-patterns/campaign-management-orchestration/event-triggered-messaging.md) |
| <img src="assets/use-case-icons/b2b/icon-abm.png" alt="ABM" width="40"> | [Account-Based Marketing Personalization](b2b/b2b-overview.md#account-based-marketing-personalization) | Personalize marketing communications for target accounts based on buying signals | [!BADGE Emerging]{type=Informative} | [B2B Audience Activation](/help/blueprints/use-case-patterns/audience-building-activation/b2b-audience-activation.md) |
| <img src="assets/use-case-icons/b2b/icon-lead-scoring.png" alt="Lead Scoring" width="40"> | [Lead Scoring and Nurturing](b2b/b2b-overview.md#lead-scoring-and-nurturing) | Automatically score leads and route high-scoring ones to sales with nurture campaigns | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/b2b/icon-content-personalization.png" alt="Content Personalization" width="40"> | [Content Personalization for Prospects](b2b/b2b-overview.md#content-personalization-for-prospects) | Personalize website content and resources based on prospect industry, role, and engagement | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| <img src="assets/use-case-icons/b2b/icon-event-registration.png" alt="Event Registration" width="40"> | [Event Registration and Follow-Up](b2b/b2b-overview.md#event-registration-and-follow-up) | Automate personalized event registration confirmations, reminders, and follow-up | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/b2b/icon-trial-conversion.png" alt="Trial Conversion" width="40"> | [Product Trial Conversion Campaigns](b2b/b2b-overview.md#product-trial-conversion-campaigns) | Engage trial users with personalized recommendations to encourage paid conversion | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/b2b/icon-customer-onboarding.png" alt="Customer Onboarding" width="40"> | [Customer Success and Onboarding](b2b/b2b-overview.md#customer-success-and-onboarding) | Personalize onboarding journeys with relevant training and resources | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/b2b/icon-competitive-replacement.png" alt="Competitive Replacement" width="40"> | [Competitive Replacement Campaigns](b2b/b2b-overview.md#competitive-replacement-campaigns) | Target prospects using competitor products with personalized migration offers | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/b2b/icon-case-study.png" alt="Case Study" width="40"> | [Case Study and ROI Personalization](b2b/b2b-overview.md#case-study-and-roi-personalization) | Deliver personalized case studies and ROI calculators based on prospect's industry | [!BADGE Emerging]{type=Informative} | [Known-Visitor Web/App Personalization](/help/blueprints/use-case-patterns/personalization/known-visitor-web-app-personalization.md) |
| | [Customer Advocacy Programs](b2b/b2b-overview.md#customer-advocacy-programs) | Identify and engage satisfied customers for references and testimonials | [!BADGE Emerging]{type=Informative} | [Multi-Step Orchestrated Journey](/help/blueprints/use-case-patterns/campaign-management-orchestration/multi-step-orchestrated-journey.md) |
| <img src="assets/use-case-icons/b2b/icon-contract-renewal.png" alt="Contract Renewal" width="40"> | [Contract Renewal Campaigns](b2b/b2b-overview.md#contract-renewal-campaigns) | Proactively engage customers approaching renewal with personalized offers | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |
| <img src="assets/use-case-icons/b2b/icon-upsell-expansion.png" alt="Upsell Expansion" width="40"> | [Upsell and Expansion Opportunities](b2b/b2b-overview.md#upsell-and-expansion-opportunities) | Identify customers ready for upgrades based on usage patterns and growth indicators | [!BADGE Advanced]{type=Caution} | [Cross-Channel Journey with Decisioning](/help/blueprints/use-case-patterns/campaign-management-orchestration/cross-channel-journey-with-decisioning.md) |

>[!ENDTABS]
